name: 'Get & Cache Dependencies'
description: 'Get the dependencies and cache them.'
inputs:
  caching:
    description: 'whether to cache dependencies or not.'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'whether thr cache was used'
    value: ${{ steps.install.outputs.cache }}

runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      if: inputs.caching == 'true'
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      id: install
      run: |
        npm ci
        echo "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT 
      shell: bash